tasks:
  - init: |
      echo 'Init: Build project'
      docker build -t svilstrup/xsltproc .
    command: |
      echo 'Command: Quick version test'
      docker run --rm -v "$PWD:/wrk" svilstrup/xsltproc --version
      